### ISSUE TITLE
Section height 

### ISSUE THREAD

**Issue by NoreenNaz1234** [Farheen-Shadani/Task-14-May#1]
https://github.com/Farheen-Shadani/Task-14-May/blob/c2171fdbcb87546b0a7f0208e18abd330ac0faac/style.css#L61

ap isko koi fixed heigth den ta ke ap mockup k jsa bna ske

**Comment by Farheen-Shadani** [comment]
miss section ko height dene ki zaroorat ni he.. mene padding di hui he jis ki waja se wo mock up ki tarhan show horaha he...agar height specific dedungi to har device pe set karni paregi jis ki waja se css long hogi to its better k mein use auto hi rehne dun ta k mjhe baar baar ye kaam na karna pare...

**Comment by NoreenNaz1234** [comment]
blkul asa he h.. lkn auto ap k aur miss k hieght main fark h, mny islea kha k pixels perfection hogi image
