### ISSUE TITLE
Paragraph 

### ISSUE THREAD

**Issue by NoreenNaz1234** [Farheen-Shadani/Task-14-May#2]
https://github.com/Farheen-Shadani/Task-14-May/blob/c2171fdbcb87546b0a7f0208e18abd330ac0faac/index.html#L65

para bhtt bold h jab k mockup main asa nh h. isko sahi kren

**Comment by Farheen-Shadani** [comment]
miss without bold wo mockup jesa show ni horaha he...bold se better match kar raha tha instead without bold....
agar ap phr b kahengi to mein unbold kardoongi..

**Comment by NoreenNaz1234** [comment]
acha ab ap dosre mockup p focus kren qk already apka laptop issue h,,  so its fine
