### ISSUE TITLE
Font family 

### ISSUE THREAD

**Issue by NoreenNaz1234** [Farheen-Shadani/Task-14-May#3]
https://github.com/Farheen-Shadani/Task-14-May/blob/c2171fdbcb87546b0a7f0208e18abd330ac0faac/style.css#L71

same font nh h farheen. ap kr skti h, ap dhonden font same

**Comment by Farheen-Shadani** [comment]
miss font wohi he jo mene boddy pe lagay hua he...par pata ni q button pe show ni horaha he...button pe alag se dubara dene se show hogaya he.. ab jab mein portfolio ko update karoongi to ye b hojaega inshaAllah..

**Comment by NoreenNaz1234** [comment]
okk
